### ISSUE TITLE
Get input from joystick

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-basestation#1]
I think getting pygame, and setting it as a dependency to the repo would be a good idea. I'm not sure what would work out of the box. If you have a logitech gamepad I would recommend you go with this (I have had no problems working with gamepads from logitech on Linux - and if it works on Linux, it will work for other OSs).

> https://www.pygame.org/docs/ref/joystick.html

Essentially, if you can write a small prototype that waits for input from joystick, and prints something on screen whenever there is a key pressed, that would set us up in a pretty good direction.

**Comment by psyomn** [comment]
If anyone can volunteer for this it would be great. Feel free to ask me for help.

**Comment by Doomfest** [comment]
Isn't this done?  @msnidal @arevans3

**Comment by msnidal** [comment]
Controller input works well on the client side.
