### ISSUE TITLE
Choose GUI library

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-basestation#2]
You will most probably want to look at two things (which come to mind):

**GTK**

> http://www.pygtk.org/

**QT**

> https://wiki.python.org/moin/PyQt

I have not looked very deeply into above links, but they should give you an idea what to look for. If you can find alternatives, post them here so we discus.

**Note**: I think you'll have less headaches working with GTK, and it might be easier to port to windows as well (windows has libraries you can install and port stuff relatively easilly).

**Comment by psyomn** [comment]
Can you guys start working on this? We're going to need this very, very, very, soon.

cc: @SamanthaSpace, @GabrieleBavaro

**Comment by Doomfest** [comment]
So which library did you guys choose for the GUI?

**Comment by SamanthaSpace** [comment]
Right now we're using PIL (Python Imaging Library), it had more online tutorials than the other 2.  Gabriele probably won't need it for the settings page though. We'll just need it for the robot control page.

**Comment by psyomn** [comment]
Take a look at `pillow` as well.

**Comment by Doomfest** [comment]
I'm taking a look at pygtk and trying it out on test-pygtk branch. 

Also, do we really need the PIL and pillow libraries?

**Comment by psyomn** [comment]
pillow is a fork of PIL IIRC, which is maintained (while PIL might be not). I'm not sure though. Take a look before sticking to something.

**Comment by Doomfest** [comment]
Hey guys, we can't just close issues without working code. If you have code for this specific issue please comment here and push your code to a branch for a pull request so we can take a look at it. I am reopening this issue untill this is done. Also, get on slack to see fi you want to talk to someone on the team in realtime.

**Comment by SamanthaSpace** [comment]
I was wondering if it mattered if it was maintained, we're working with an older version of python so why not an older version of PIL?

**Comment by SamanthaSpace** [comment]
Also I thought this was done.  It's marked as research, I didn't think that included writing a whole new branch.

**Comment by Doomfest** [comment]
So are you guys using TK or pygtk or QT? I did a basic gui with pygtk and it seems really easy. Did you take a look at it?

**Comment by Doomfest** [comment]
Do you guys want to meetup and explain which gui tool you used and why? Like discuss the pros and cons of each one?

**Comment by Doomfest** [comment]
We are using pygtk.
