### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-basestation#22]
@Doomfest Yo, can you remove anything that is not used? There's a few branches which don't seem like they are being used/up to date.

**Comment by Doomfest** [comment]
I'll have to go over with them wiht amrk and arielle.

On Tue, Sep 22, 2015 at 6:12 PM, Simon notifications@github.com wrote:

> Assigned #22
> https://github.com/space-concordia-robotics/robotics-basestation/issues/22
> to @Doomfest https://github.com/Doomfest.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/space-concordia-robotics/robotics-basestation/issues/22#event-416406284
> .

## 

George G.

**Comment by psyomn** [comment]
I think you did this. Just close if you're done.

**Comment by Doomfest** [comment]
I cleaned the branches on Saturday. There are a few that some people are working on.
