### ISSUE TITLE
Add dependencies to use GUI for basestation lib

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-basestation#3]
You can see in a similar project how dependencies are added:

> https://github.com/jmcarp/robobrowser/blob/master/setup.py

The area of interest is particularly in the setup function:

``` python
""" First, the requirements may be set at the top like this """

REQUIREMENTS = [
    'beautifulsoup4>=4.3.2',
    'requests>=2.6.0',
    'six>=1.9.0',
    'Werkzeug>=0.10.4',
]

""" ... and then the variable is set to the `install_requires` """

setup(
    # ... bunch of stuff ...
    package_dir={'robobrowser': 'robobrowser'},
    include_package_data=True,
    install_requires=REQUIREMENTS,
    tests_require=TEST_REQUIREMENTS,
    license='MIT',
    # ... more stuff
)

""" You'll want to include PyGTK this way """
```

**Comment by Doomfest** [comment]
@psyomn Please check the test-pygtk branch. Look at the code and tell me if its okay. Also, I have no clue how to use setup.py to import libraries for all computers. I just did import in the test-pygtk.py file to going.

**Comment by psyomn** [comment]
> Also, I have no clue how to use setup.py to import libraries for all computers

I don't understand what you're saying exactly. Read what I posted at the top carefully. To specify dependencies, you add a string array into the `install_requires`. So if you have dep version 1, you'd have:

``` python
    ...
    install_requires=["dep>=1.0"]
    ...
```

And you can add more. I had created another branch where I'm doing this, but I didn't iron out some problems, so you can't exactly test it out.

**Comment by Doomfest** [comment]
Hey guys, we can't just close issues without working code. If you have code for this specific issue please comment here and push your code to a branch for a pull request so we can take a look at it. I am reopening this issue untill this is done. Also, get on slack to see fi you want to talk to someone on the team in realtime.

This is clearly not done. Why is it closed?

**Comment by SamanthaSpace** [comment]
I did forget about having to have it work on multiple operating systems.

**Comment by SamanthaSpace** [comment]
Do we need dependencies? Do dependencies make the program auto-install the file, or does the user have to install our program and the dependencies?  You didn't show where to put the dependencies in the code folder, so I thought this meant they were sought externally, like online.  Online install locations are unreliable, I would rather put the library options right into the program.  

I did this for Mac.  I could name the libraries for different systems as different classes within the program, and do an if statement within the main code to have it choose which library to use depending on the system.  This way it would all be in one file.  Making all seven of us download every library every time we make a change on any part of the code seems impractical.  Maybe I'm misunderstanding dependencies and that is what they do?

**Comment by Doomfest** [comment]
We will use simon's setup.py file. We will put our dependencies in there. You will need to run the command " python2.7 setup.py install --user"  to get all the dependencies before programming. This will keep the dependencies up-to-date. Please read the README file.

**Comment by msnidal** [comment]
I tried to add setup.py as a dependency as Simon suggested above, but it seems setuptools does not play well with PyGTK, as it produced an error on output. Here's the relevant output:

http://pastebin.com/v8vzKTJf

Note the error at the bottom. We'll need to look into this.
