### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by tamarindd** [space-concordia-robotics/robotics-basestation#32]
There should be some tests for joystick_listener, mjpg, and send_command. Possibly base_window also.

**Comment by psyomn** [comment]
Emulating joystick events sounds really cool, really fun. You could do this
programmatically, or you could record events of a joystick, and then feed
them to your tests.

**Comment by msnidal** [comment]
Subdivided this task into the following issues:

#39 
#40 
#41
