### ISSUE TITLE
Create a small test gui to try out TK.

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-basestation#5]
This is to try the TK library to see if it is a good candidate for the gui and features that we need.
Anyone can do this. I will move onto this when I am done trying out pygtk.

**Comment by Doomfest** [comment]
Hey guys, we can't just close issues without working code. If you have code for this specific issue please comment here and push your code to a branch for a pull request so we can take a look at it. I am reopening this issue untill this is done. Also, get on slack to see fi you want to talk to someone on the team in realtime.

Please comment why you closed this issue.????

**Comment by SamanthaSpace** [comment]
The code includes a library already PIL, although I did forget to make it compatible with different systems.

**Comment by Doomfest** [comment]
I will like someone to make a TK gui example like i did for pygtk.

**Comment by Doomfest** [comment]
I am closing this  since we are going to use pygtk for the gui.
