### ISSUE TITLE
Fix setup.py file

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-basestation#7]
Add requirements and uncomment the ones in it. Also, fix any missing modules when doing this.

**Comment by msnidal** [comment]
I added a roboticsnet requirement and fixed the URL. Leaving this open since I'm not sure about missing modules if any

**Comment by Doomfest** [comment]
I added "import pygame" for now to get it running. We should see if theres a better way to do this. (use requirements)

**Comment by psyomn** [comment]
Talk to Mark

**Comment by Doomfest** [comment]
@msnidal
