### ISSUE TITLE
Add buttons and google map caching working on the GUI. (first version of GUI)

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-basestation#9]
We should be able to have some buttons and a google map working on the gui.

The buttons should be able to send some movement commands to the server on the rover.
Also show some coordinates on the GUI. (Any number for now. The GPS sensor isnt done)
Also try to add a small rover icon on the map.

**Comment by Doomfest** [comment]
@wechu  @GabrieleBavaro @msnidal @arevans3

**Comment by msnidal** [comment]
We should also check if Google maps is the best solution - does the competition provide satellite pictures? It's worth checking.

**Comment by Doomfest** [comment]
Doesn't google maps have satellite pictures?

**Comment by Doomfest** [comment]
Updated specifications for this task:

Add a map (google maps best one?)
Show some coordinates on the GUI.
Try to add a rover icon on the map.

**Comment by msnidal** [comment]
Buttons were done a long time ago but the map was never developed. Split that task and merged into #42 (not using Google Maps)
